USE MASTER

CREATE DATABASE QLTV
USE QLTV

CREATE TABLE SACH(
    MASACH NCHAR(20) PRIMARY KEY,
    TENSACH NVARCHAR(50),
    SOTRANG INT,
    SLTON INT
)

CREATE TABLE PM(
    MAPM NCHAR(20) PRIMARY KEY,
    NGAYM DATE,
    HOTENDG NVARCHAR(50)
)

CREATE TABLE SACHMUON(
    MAPM NCHAR(20),
    MASACH NCHAR(20),
    SONGAYMUON INT

    CONSTRAINT PK_MAPM_MASACH PRIMARY KEY(MAPM, MASACH),
    CONSTRAINT FK_MAPM FOREIGN KEY (MAPM) REFERENCES PM(MAPM) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_MASACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH) ON UPDATE CASCADE ON DELETE CASCADE
)

INSERT INTO SACH VALUES
(N'S01', N'SÁCH 1', 1000, 100),
(N'S02', N'SÁCH 2', 1500, 2000)

INSERT INTO PM VALUES
(N'PM01', '2021-8-23', N'NGUYỄN NHẬT MINH'),
(N'PM02', '2021-5-24', N'NGUYỄN NHẬT NAM')

INSERT INTO SACHMUON VALUES
(N'PM01', N'S01', 30),
(N'PM01', N'S02', 40),
(N'PM02', N'S01', 35),
(N'PM02', N'S02', 60)

SELECT * FROM SACH
SELECT * FROM PM
SELECT * FROM SACHMUON

CREATE VIEW CAU2
AS
    SELECT SACH.MASACH, PM.MAPM, TENSACH, DATEADD(DAY, SONGAYMUON, NGAYM) AS NGAYHETHAN
    FROM SACH INNER JOIN SACHMUON
    ON SACH.MASACH = SACHMUON.MASACH
    INNER JOIN PM
    ON SACHMUON.MAPM = PM.MAPM
    WHERE DATEADD(DAY, SONGAYMUON, NGAYM) <= GETDATE()

SELECT * FROM CAU2

CREATE TRIGGER CAU4
ON SACHMUON
FOR INSERT
AS 
    BEGIN
        UPDATE SACH
        SET SLTON = SLTON - 1
        FROM SACH INNER JOIN inserted
        ON SACH.MASACH = inserted.MASACH
    END